# Generated by Django 6.0.5 on 2026-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_auto_20260506_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='installationappointment',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='installationappointment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='regions',
        ),
        migrations.AddField(
            model_name='technician',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='technician',
            name='speciality',
            field=models.CharField(choices=[('CAMERA', 'Installation Caméra'), ('NETWORK', 'Réseau & Connectivité'), ('POWER', 'Alimentation Électrique'), ('GENERAL', 'Généraliste')], default='GENERAL', max_length=20),
        ),
        migrations.DeleteModel(
            name='AgentPerimeter',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
