# Generated by Django 5.2.14 on 2026-05-07 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0005_fieldperimeter_subscription_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nin', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('Dakar', 'Dakar'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaffrine', 'Kaffrine'), ('Kaolack', 'Kaolack'), ('Kedougou', 'Kédougou'), ('Kolda', 'Kolda'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis'), ('Sedhiou', 'Sédhiou'), ('Tambacounda', 'Tambacounda'), ('Thies', 'Thiès'), ('Ziguinchor', 'Ziguinchor')], max_length=50)),
                ('locality', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('farm_size', models.CharField(blank=True, help_text="Superficie de l'exploitation", max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=12)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-created_at'],
            },
        ),
    ]
