# Generated by Django 5.2.14 on 2026-05-07 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0006_agentregistrationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE_AGENT', 'Création agent'), ('UPDATE_AGENT', 'Modification agent'), ('DELETE_AGENT', 'Suppression agent'), ('ACTIVATE_AGENT', 'Activation agent'), ('DEACTIVATE_AGENT', 'Désactivation agent'), ('APPROVE_REQUEST', 'Approbation demande'), ('REJECT_REQUEST', 'Rejet demande'), ('CREATE_APPOINTMENT', 'Création rendez-vous'), ('UPDATE_APPOINTMENT', 'Modification rendez-vous'), ('ASSIGN_TECHNICIAN', 'Assignation technicien')], max_length=30)),
                ('target_type', models.CharField(help_text="Type d'objet (User, AgentRegistrationRequest, etc.)", max_length=50)),
                ('target_id', models.CharField(help_text="ID de l'objet ciblé", max_length=100)),
                ('target_name', models.CharField(help_text="Nom/description de l'objet", max_length=255)),
                ('details', models.JSONField(blank=True, help_text='Détails supplémentaires', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='surveillanc_created_3173c1_idx'), models.Index(fields=['user', '-created_at'], name='surveillanc_user_id_29f6e9_idx'), models.Index(fields=['action', '-created_at'], name='surveillanc_action_999bca_idx')],
            },
        ),
    ]
