# Generated by Django 5.2.14 on 2026-05-06 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('Dakar', 'Dakar'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaffrine', 'Kaffrine'), ('Kaolack', 'Kaolack'), ('Kedougou', 'Kédougou'), ('Kolda', 'Kolda'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis'), ('Sedhiou', 'Sédhiou'), ('Tambacounda', 'Tambacounda'), ('Thies', 'Thiès'), ('Ziguinchor', 'Ziguinchor')], max_length=50)),
                ('locality', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SCHEDULED', 'Planifié'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous installation',
                'verbose_name_plural': 'Rendez-vous installations',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerimeterAgricole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du périmètre')),
                ('region', models.CharField(choices=[('Dakar', 'Dakar'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaffrine', 'Kaffrine'), ('Kaolack', 'Kaolack'), ('Kedougou', 'Kédougou'), ('Kolda', 'Kolda'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis'), ('Sedhiou', 'Sédhiou'), ('Tambacounda', 'Tambacounda'), ('Thies', 'Thiès'), ('Ziguinchor', 'Ziguinchor')], max_length=50, verbose_name='Région')),
                ('locality', models.CharField(max_length=120, verbose_name='Localité')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('surface_hectares', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Surface (hectares)')),
                ('culture_type', models.CharField(choices=[('CEREAL', 'Céréales'), ('LEGUME', 'Légumes'), ('FRUIT', 'Fruits'), ('TUBERCULE', 'Tubercules'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de culture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('installation_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'installation")),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Dernière maintenance')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perimetres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Périmètre Agricole',
                'verbose_name_plural': 'Périmètres Agricoles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la caméra')),
                ('camera_index', models.IntegerField(default=0, verbose_name='Index de la caméra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('position_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Position')),
                ('perimeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='surveillance.perimeteragricole')),
            ],
            options={
                'verbose_name': 'Caméra',
                'verbose_name_plural': 'Caméras',
            },
        ),
    ]
