# Generated by Django 5.2.14 on 2026-05-06 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='perimeter',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='position_description',
        ),
        migrations.AddField(
            model_name='camera',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Durée estimée en heures', null=True),
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AgentPerimeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du champ')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('coordinates', models.JSONField(help_text='Coordonnées du périmètre au format [[lat, lng], [lat, lng], ...]')),
                ('center_lat', models.FloatField(verbose_name='Latitude centrale')),
                ('center_lng', models.FloatField(verbose_name='Longitude centrale')),
                ('surface_area', models.FloatField(blank=True, null=True, verbose_name='Surface (hectares)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perimeter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Périmètre agricole',
                'verbose_name_plural': 'Périmètres agricoles',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('danger_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('frame_capture', models.URLField(blank=True, max_length=500, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_alert', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='surveillance.camera')),
            ],
            options={
                'verbose_name': 'Détection',
                'verbose_name_plural': 'Détections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='surveillance.detection')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('BASIC', 'Basique'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Entreprise')], default='BASIC', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('camera_rental', models.BooleanField(default=False, verbose_name='Location de caméra')),
                ('premium_support', models.BooleanField(default=False, verbose_name='Support premium')),
                ('advanced_analytics', models.BooleanField(default=False, verbose_name='Analyses avancées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speciality', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('experience_years', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('regions', models.JSONField(default=list, help_text="Liste des régions d'intervention")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
            },
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='surveillance.technician'),
        ),
        migrations.DeleteModel(
            name='PerimeterAgricole',
        ),
    ]
