# Generated by Django 5.2.14 on 2026-05-06 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_agent(apps, schema_editor):
    """Set default agent for cameras without agent"""
    Camera = apps.get_model('surveillance', 'Camera')
    User = apps.get_model('users', 'CustomUser')
    
    # Get first user as default or create a system user
    default_user = User.objects.first()
    
    if default_user:
        Camera.objects.filter(agent__isnull=True).update(agent=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_remove_camera_perimeter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, ensure all cameras have an agent
        migrations.RunPython(set_default_agent),
        
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='camera',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL),
        ),
    ]
