# Generated by Django 5.2.14 on 2026-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='installed_at',
            field=models.DateTimeField(blank=True, help_text="Date d'installation de la caméra", null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude GPS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude GPS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text="Date de complétion de l'installation", null=True),
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='equipment_installed',
            field=models.JSONField(blank=True, help_text='Liste des équipements installés', null=True),
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='installation_notes',
            field=models.TextField(blank=True, default='', help_text="Notes techniques d'installation"),
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude GPS du lieu', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='installationappointment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude GPS du lieu', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_AGENT', 'Création agent'), ('UPDATE_AGENT', 'Modification agent'), ('DELETE_AGENT', 'Suppression agent'), ('ACTIVATE_AGENT', 'Activation agent'), ('DEACTIVATE_AGENT', 'Désactivation agent'), ('APPROVE_REQUEST', 'Approbation demande'), ('REJECT_REQUEST', 'Rejet demande'), ('CREATE_APPOINTMENT', 'Création rendez-vous'), ('UPDATE_APPOINTMENT', 'Modification rendez-vous'), ('ASSIGN_TECHNICIAN', 'Assignation technicien'), ('COMPLETE_INSTALLATION', 'Installation terminée'), ('CREATE_CAMERA', 'Création caméra'), ('CREATE_PERIMETER', 'Création périmètre')], max_length=30),
        ),
    ]
